### ISSUE TITLE
Write API docs

### ISSUE THREAD

**Issue by lusy** [descentis/kdap#13]
Hi, your library looks very useful (just saw your OpenSym presentation). What am I missing though is documentation of what the library can do. (If it is already in the making, sorry for the duplication).
Cheers, Lusy

**Comment by descentis** [comment]
Hi, thanks for your reply. You can find the documentation here: https://kdap.readthedocs.io/en/latest/
We are still building the tutorial section of the documentation and adding the description of few methods. We are working on it and will release the completed doc soon.

**Comment by descentis** [comment]
Hi @lusy , the documentation is in place. Kindly have a look. I'm closing this issue for now.
